title: Zero Knowledge Proof
description: "From Zero to Finite Fields: A Journey into Cryptography"
author: Stephen Dorman
baseurl: "/crypto-learning-lab"
url: "https://stephendor.github.io"

permalink: /:categories/:year/:month/:day/:title/
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
excerpt_separator: "<!--more-->"
timezone: Europe/London

theme: null

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - tufte-theme

# Enable MathJax (see conditional in `head.html`)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      mathjax: true

