nname: Build and Deploy Jekyll Blog

on:
  push:
    branches:
      - main  # or 'master' if that's your default

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Match your dev version
          bundler-cache: true

      - name: Install dependencies
        run: |
          cd blog
          bundle install

      - name: Build site with Jekyll
        run: |
          cd blog
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog/_site
          publish_branch: gh-pages
